[2022-09-24T17:10:16.703+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj manual__2022-09-24T17:10:15.356796+00:00 [queued]>
[2022-09-24T17:10:16.717+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj manual__2022-09-24T17:10:15.356796+00:00 [queued]>
[2022-09-24T17:10:16.718+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-24T17:10:16.718+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-24T17:10:16.718+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-24T17:10:16.737+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.cast_obj> on 2022-09-24 17:10:15.356796+00:00
[2022-09-24T17:10:16.743+0000] {standard_task_runner.py:54} INFO - Started process 252 to run task
[2022-09-24T17:10:16.748+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.cast_obj', 'manual__2022-09-24T17:10:15.356796+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/dbt_try.py', '--cfg-path', '/tmp/tmpbtq5q2ut']
[2022-09-24T17:10:16.749+0000] {standard_task_runner.py:83} INFO - Job 78: Subtask model.migrate_to_dbt.cast_obj
[2022-09-24T17:10:16.750+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_try.py
[2022-09-24T17:10:16.752+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 78 for task model.migrate_to_dbt.cast_obj (Dag 'dbt_dag' could not be found; either it does not exist or it failed to parse.; 252)
[2022-09-24T17:10:16.772+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-24T17:10:16.811+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
