[2022-09-23T17:02:01.207+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract.create_table manual__2022-09-23T17:01:59.952686+00:00 [queued]>
[2022-09-23T17:02:01.218+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: extract.create_table manual__2022-09-23T17:01:59.952686+00:00 [queued]>
[2022-09-23T17:02:01.218+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-23T17:02:01.218+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-23T17:02:01.218+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-23T17:02:01.229+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2022-09-23 17:01:59.952686+00:00
[2022-09-23T17:02:01.234+0000] {standard_task_runner.py:54} INFO - Started process 720 to run task
[2022-09-23T17:02:01.237+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'extract', 'create_table', 'manual__2022-09-23T17:01:59.952686+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmphqga754a']
[2022-09-23T17:02:01.237+0000] {standard_task_runner.py:83} INFO - Job 102: Subtask create_table
[2022-09-23T17:02:01.238+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/extract.py
[2022-09-23T17:02:01.443+0000] {task_command.py:384} INFO - Running <TaskInstance: extract.create_table manual__2022-09-23T17:01:59.952686+00:00 [running]> on host be000c34f638
[2022-09-23T17:02:01.514+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=yishaktadele
AIRFLOW_CTX_DAG_ID=extract
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-23T17:01:59.952686+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-23T17:01:59.952686+00:00
[2022-09-23T17:02:01.522+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2022-09-23T17:02:01.525+0000] {sql.py:315} INFO - Running statement: -- CREATE DATABASE IF NOT EXISTS `city_traffic`;
CREATE TABLE IF NOT EXISTS  objects (
   track_id INT PRIMARY KEY,
   type varchar(20),
   traveled_d FLOAT,
   avg_speed FLOAT,
   lat FLOAT,
   lon FLOAT,
   speed FLOAT, 
   lon_acc FLOAT,
   lat_acc FLOAT,
   time FLOAT
);, parameters: None
[2022-09-23T17:02:01.527+0000] {postgres.py:94} INFO - NOTICE:  relation "objects" already exists, skipping

[2022-09-23T17:02:01.536+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=extract, task_id=create_table, execution_date=20220923T170159, start_date=20220923T170201, end_date=20220923T170201
[2022-09-23T17:02:01.569+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-09-23T17:02:01.590+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
