[2022-09-24T13:08:10.424+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: migrate_data.migrate manual__2022-09-24T13:08:08.634693+00:00 [queued]>
[2022-09-24T13:08:10.435+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: migrate_data.migrate manual__2022-09-24T13:08:08.634693+00:00 [queued]>
[2022-09-24T13:08:10.435+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-24T13:08:10.435+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-09-24T13:08:10.435+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-24T13:08:10.449+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): migrate> on 2022-09-24 13:08:08.634693+00:00
[2022-09-24T13:08:10.457+0000] {standard_task_runner.py:54} INFO - Started process 371 to run task
[2022-09-24T13:08:10.468+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'migrate_data', 'migrate', 'manual__2022-09-24T13:08:08.634693+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/migrate.py', '--cfg-path', '/tmp/tmpncdp1436']
[2022-09-24T13:08:10.468+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask migrate
[2022-09-24T13:08:10.469+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/migrate.py
[2022-09-24T13:08:40.596+0000] {timeout.py:68} ERROR - Process timed out, PID: 371
[2022-09-24T13:08:41.097+0000] {dagbag.py:330} ERROR - Failed to import: /opt/***/dags/migrate.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/migrate.py", line 3, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 143, in <module>
    from pandas.io.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/api.py", line 8, in <module>
    from pandas.io.excel import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/__init__.py", line 6, in <module>
    from pandas.io.excel._odswriter import ODSWriter as _ODSWriter
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_odswriter.py", line 15, in <module>
    from pandas.io.formats.excel import ExcelCell
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1394, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/***/dags/migrate.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://***.apache.org/docs/apache-***/2.4.0/best-practices.html#top-level-python-code
* https://***.apache.org/docs/apache-***/2.4.0/best-practices.html#reducing-dag-complexity, PID: 371
[2022-09-24T13:08:43.007+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task migrate (Dag 'migrate_data' could not be found; either it does not exist or it failed to parse.; 371)
[2022-09-24T13:08:43.649+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-24T13:08:43.733+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
